### ISSUE TITLE
Graphically design the buttons for the website so they react when scrolled over

### ISSUE THREAD

**Issue by chizzyx** [CSAllenISD/2023-ISP-MoodAndGrasp#21]

**Comment by turner-william** [comment]
This is a good idea and will not be too hard to implement.

**Comment by Neb-Seniah** [comment]
Could you go into further detail about how the buttons react? do they grow in size or get brighter?

**Comment by chizzyx** [comment]
I was thinking grow bigger in size

**Comment by KaiosKen** [comment]
I think we should do that.
