### ISSUE TITLE
see if the implentation of a chat bot is possible so students who are flagged as depressed can talk to somebody (like a hope sqaud member)

### ISSUE THREAD

**Issue by chizzyx** [CSAllenISD/2023-ISP-MoodAndGrasp#36]

**Comment by Neb-Seniah** [comment]
How would someone be flagged as depressed? I do like the idea of a chat bot but I do wonder if it would be better implemented to talk with someone if they say they are sad on a particular day, however this depends on when in class students would input information.

**Comment by chizzyx** [comment]
I figured the website would track users emotions day by day and compile them by the end of the week. Then compile that data week by week. Users are repeatedly low in spirits would be offered the suggestion to talk to somebody. However, I do like your suggestion more of allowing users to talk to someone if they are sad on a particular day rather than waiting a week or 2.

**Comment by Neb-Seniah** [comment]
Yeah, I do think that the main issue with a chatbot talking to people flagged as depressed is that they could just ignore the bot, also I think I need more details on the flagging process, since just counting up days where someone said they were sad wouldn't work efficiently.
It should be added that this isn't a priority for the MVP.

**Comment by chizzyx** [comment]
Nobody would be obligated to talk to the bot just something for people who want somebody to talk to. And absolutely this isnt a priority for the mvp just something I think would be cool/helpful for both the user and for hope squad helping them get in touch with people who need somebody to talk to. If we finish with time to spare this is something we could work on.

**Comment by KaiosKen** [comment]
Yeah uh this not getting done 💀
