### ISSUE TITLE
Create a an updatable graph

### ISSUE THREAD

**Issue by dottiexe** [CSAllenISD/2023-ISP-MoodAndGrasp#40]
Create a graph that can be visually updated based on user made changes in a database. This does not need to be animated.

**Comment by Neb-Seniah** [comment]
I might've mentioned it somewhere else, but I think for the graph we might need to make the y-values (amount of people submitting the answer), and therefore the bar graph, scale with how many people select an answer, it shouldn't be a priority but we might run into issues later if we do not do it. Also I agree that moving the graph smoothly should only be done if we find the time.
