### ISSUE TITLE
User account creation system

### ISSUE THREAD

**Issue by dottiexe** [CSAllenISD/2023-ISP-MoodAndGrasp#42]
Finish creating a register page, that will store users information into a database. When the users attempt to login, the info should be checked against the contents of the database, and the webstite should react accordingly if the user info matches or not.

**Comment by Neb-Seniah** [comment]
I know it shouldn't be part of the MVP, but are we considering a CAPTCHA-Like system for spam prevention? Also I am not sure how google auto login stuff works, so if that is something we have to specifically set up and it doesn't take much time, then we probably should.

**Comment by KaiosKen** [comment]
@Neb-Seniah I already made a user account creation and signup page, but that's a good idea, so I'll open a new issue about that and work on it. I will close this issue since it has been completed
