### ISSUE TITLE
Design the About Page for our website

### ISSUE THREAD

**Issue by KaiosKen** [CSAllenISD/2023-ISP-MoodAndGrasp#65]
I already have a page with a View and link in the menu dropdown, but it is currently empty. I would like something that describes what our website does and why we chose to make it. I'd rather it not be a block of text but if you don't know how to style HTML you can simply write the text and I or another developer can make the page visually appealing.

<img width="1440" alt="Screenshot 2023-04-13 at 9 59 34 PM" src="https://user-images.githubusercontent.com/89750634/231930473-7e90f768-a29d-4d52-a4bb-fed8d2224d77.png">

**Comment by chizzyx** [comment]
i will go down the road

**Comment by chizzyx** [comment]
leave it to me

**Comment by chizzyx** [comment]
never fear nahom is here
