### ISSUE TITLE
10 dollar debt

### ISSUE THREAD

**Issue by chizzyx** [CSAllenISD/2023-ISP-MoodAndGrasp#66]
it seems that some members of this isp do not respect other members of this isp enough to pay them back the money they owe them. one member owes another member of this group 10 dollars for chic-fil-a and refuses to pay them back. please resolve this.

**Comment by GannonMurray06** [comment]
It seems there must be a confusion in this ISP issue. One member of our ISP members demand 10 dollars for chick-fil-a***, in which that chick-fil-a was an offer to another member of our group, as well as payment for gas money, which the other person does not understand. Furthermore, if that member is wanting a payment for something that he offered, he was offered many meals of school food, in which he now has to pay 50 dollars instead. Or, the two members can completely disregard all debt and no longer owe anyone anything. Please resolve this immediately.

**Comment by GannonMurray06** [comment]
2v1
