### ISSUE TITLE
Filler Questions

### ISSUE THREAD

**Issue by mxrkay** [CSAllenISD/2023-ISP-MoodAndGrasp#85]
"filler" questions that will use the preset:
Very
Somewhat
Meh
Hardly
Not at all

will need a different set of emojis because they do not show emotion.

- communicate with one another to decide on the emojis
- create the emojis (graphic designers)
- commit and upload them to the corresponding questions

Idea #1:
![wwwwwww](https://user-images.githubusercontent.com/131902400/234658983-1ca44501-e3aa-4276-8249-1f30ce188062.jpeg)

This could work, although the emojis are similar to the ones we already have. If we would want more diversity, we need to create something better.

**Comment by KaiosKen** [comment]
This is a nice idea, but with the website entering its last stages I think we need to move past filler questions and get working on the final product
